### PR TITLE
Added the Playlist feature

### PR DESCRIPTION
**Pull request by byjg**
I created a feature that supports playlist. This feature does not break compatibility with previous installed Audio5JS versions, just adding the playlist. 

So, the resource still working:

```javascript
audio5.load('/song');
audio5.play();
``` 

And added the methods:

- loadPlaylist(array): loads an array that represents the playlist
- startPlaylist(): start playing the playlist
- clearPlaylist() : clear the playlist
- current(): get the index of the current track in the playlist
- next(): move to the next track of the playlist
- previous(): move to the previous track of the playlist

An example how it will be is:

```javascript
var list = [
    'song1.mp3',
    'song2.mp3'
];
audio5.loadPlaylist(list);
audio5.startPlaylist();
```

After the end of the current track the system will play automatically to the next track. 
The play(), pause(), seek(), continue to work as the expected with the current track.

### CODE REVIEW

**Comment by zohararad** [comment]
Thanks a lot for this.
I'm actually not 100% sure this is within the scope of Audio5js, as HTML5 Audio doesn't have playlist capabilities.

I'm willing to consider adding this as an external module rather than a core addition.

**Comment by byjg** [comment]
Yeah, I know that HTM5 has not playlist capabilities but i tried to less
intrusive I could and this feature is awesome and lacks on HTML5 audio
component.

I am figuring out here. I could create an inheritance of Audio5, like
Audio5Plus or something else. Maybe this could be integrate to your library
without change the core like you want.

But right now I am using this feature and it is important to me. If will
integrate to your excellent library as I implemented or as a module will be
very welcome.

Em 14 de jul de 2017 12:41 AM, "zohararad" <notifications@github.com>
escreveu:

Thanks a lot for this.
I'm actually not 100% sure this is within the scope of Audio5js, as HTML5
Audio doesn't have playlist capabilities.

I'm willing to consider adding this as an external module rather than a
core addition.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zohararad/audio5js/pull/85#issuecomment-315261581>, or mute
the thread

**Comment by zohararad** [comment]
Ok, Let's do this - If you could add a module that extends the core object with the playlist capabilities, and add tests to support it, I think this addition would be most welcome, and beneficial to other users out there.

I think including it in the core library is not in the spirit of the original project's purpose, and might be redundant to some users, so a small external module that adds this functionality is a good compromise IMO.

Please also be ready to address any bugs that might occur after adding this module, and add a section in the README to explain how to use it.

**Comment by byjg** [comment]
Great! But I'll ask you to help me defining the architecture you are imagining. I am starting with JavaScript right now. Could you create a skeleton for me and I evolve from this point?

**Comment by zohararad** [comment]
Hmm... I'm a bit busy with other stuff. I suggest you read the code and see how I wrote it, and copy the style. I'll provide comments on your PR as relevant

**Comment by byjg** [comment]
Hi, 

I am here again. So, I completely refactored the code of playlist, added  a bunch of tests and wrote a README with the playlist feature. 

Basically I do not change the API, and I maintained your idea. So, I based on the idea of other similar software like (https://github.com/goldfire/howler.js#documentation) and write the playlist feature. 

Now you can load as you did before:

```
audio.load('youraudio.mp3');
```
or load an array:
 
```
audio.load(['audio1.mp3', 'audio2.mp3', 'audio3.mp3']);
```
and added three methods for support the list:

- current()
- next()
- previous()

That's does not change your current Audio5js behavior neither change your main idea. 

I really would appreciate you consider approve this PR now :)

**Comment by zohararad** [comment]
Hey. Thanks for the PR, but as I wrote above, I really think that the core purpose of Audio5js is to provide a compatibility layer to HTML5 audio for browsers that don't support it natively.

As such, adding a playlist to the core library feels a little foreign and I would really love this feature to be added as an external library / plugin.

So an example invocation should be something like:

```
var player = new Audio5js.Playlist({
  urls: [....],
  ready: function(){}
});
```

Where `Audio5js.Playlist` is your code that wraps the playlist functionality and triggers Audio5js internally.

Regarding your code:

- using `instanceof array` to check if a variable is an array isn't the correct way on older browsers (which this library must support). Please read [here](https://stackoverflow.com/questions/22289727/difference-between-using-array-isarray-and-instanceof-array)
- currently your tests replicate the existing specs with a playlist, rather than testing your added behaviour. I would expect tests to check that the playlist features work, rather than the core Audio features work (since they are already tested).

Please let me know if you can work out how to put the playlist behaviour into an external library or need me to provide some base code for you.

Thanks again for the great work, and apologies for being a little strict on accepting your PR - I don't mean to frustrate you, just to make sure the library stays true to its original purpose

**Pull request closed without merging**
