### PR TITLE
Playlist Feature v2

### PR DESCRIPTION
**Pull request by byjg**
As the PR #85 was not accepted I am trying do a new implementation. 

This is missing tests, but the base is done. I hope this is the way.

### CODE REVIEW

**Comment by zohararad** [comment]
This is much better, thank you very much!

A few requests / comments:

1. Can you please move this code into a separate file? So it can be loaded optionally?
2. Why are you creating a new Audio5js instance for every file? It seems wasteful and you're not destroying old instances as well. I would expect the playlist to have a single Audio5js instance, and simply load and unload files based on the list

**Comment by byjg** [comment]
> Can you please move this code into a separate file? So it can be loaded optionally?

OK

> Why are you creating a new Audio5js instance for every file? It seems wasteful and you're not destroying old instances as well. I would expect the playlist to have a single Audio5js instance, and simply load and unload files based on the list

It is safer create a new object instead to reuse a previous object created. I'll destroy the old object before to create a new one.

**Comment by zohararad** [comment]
I'm not seeing any changes about reusing a single audio instance or separating this functionality into an external module

**Comment by byjg** [comment]
Hey Man,

All suggestions were made a few days ago. Just access:
https://github.com/zohararad/audio5js/pull/89/commits and you'll see all
changes i've done:

   - 79daf1a
   <https://github.com/zohararad/audio5js/pull/89/commits/79daf1ae95699c1ade61f7dc65bdf33a0e42d8af>:
Destroy
   the old object before create a new one.
   - cececa2
   <https://github.com/zohararad/audio5js/pull/89/commits/cececa23a3c40d3e2c4dc6805572abf21459b1c7>:
   Split into two separate files
   - 6f881c6
   <https://github.com/zohararad/audio5js/pull/89/commits/6f881c64895b0c79af6a7c9218bf32634d032095>:
   Added to grunt

And more 4 or 5 different commits in there.

I have to evolve and I would like to share this with you. But, sincerely, I
believe the playlist feature is not important for you and you are not
comfortable in to have it next  to your audio5js code.

I'll continuing implementing new features, but I'll not share these with
you anymore.

Thank you.

**Comment by zohararad** [comment]
Ok - this is up to you. As I explained before, I'm happy to add this feature but under certain conditions or guidelines.

I understand if you wish to continue down your own path. Feel free to open a PR if your code meet the requirements I outlined, or even create a repo for your plugin only and I'll link from the README. Up to you

**Pull request closed without merging**
